version: '2'
services:
  rainloop:
    container_name: rainloop
    image: hardware/rainloop
    restart: always
    volumes:
    - rainloop_data:/rainloop/data
  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./ssl:/tmp/ssl:ro
    env_file:
    - .env
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

  entry:
    container_name: entry
    image: abiosoft/caddy:0.10.4
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./entry/Caddyfile:/etc/Caddyfile
      - caddy_data:/root/.caddy
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  rainloop_data:
    driver: local
  caddy_data:
    driver: local