#testing
---
- name: install nginx
  hosts: 192.168.1.62
  tasks:
        - name: install nginx php
          apt:
                  name:
                        - nginx
                        - php7.0
                        - php7.0-fpm
                        - vim
                  state: present

        - name: download roundcube mail
          get_url:
                   url: https://github.com/roundcube/roundcubemail/releases/download/1.3.7/roundcubemail-1.3.7-complete.tar.gz
                   dest: /var/www/html
                   checksum: sha256:31bd37d0f89dc634064f170c6ed8981c258754b6f81eccb59a2634b29d0bb01c

        - name: decompress roundcube
          unarchive:
            src: /var/www/html/roundcubemail-1.3.7-complete.tar.gz
            dest: /var/www/html
