    - name: install dependencies
      apt:
        name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - software-properties-common
            - python-pip
            - python-apt
            - openssl
        state: present
    - name: adding apt-key for docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: adding docker repo list
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: install docker-ce and docker-compose
      apt:
        name:
            - docker-compose
            - docker-ce
        state: present

    - name: adding apt-key for kube
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: adding kube repo list
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install docker-ce and docker-compose
      apt:
        name:
            - kubeadm
            - kubectl
            - kubelet
        state: present

    - name: Commenting a line using the regualr expressions in Ansible.
      replace:
        path: /etc/fstab
        regexp: '(^(?!#).*swap.*sw.*)'
        replace: '#\1'

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
