    - name: Check if node has been added
      local_action: command ssh {{MasterPubIP}} kubectl get nodes
      register: Clusterinfo
      changed_when: False

    - name: Record hostname
      shell: hostname
      register: EachNodesName
      changed_when: False

    - name: Copy cluster token from master
      local_action: command ssh {{MasterPubIP}} kubeadm token create --print-join-command
      register: token
      when: Clusterinfo.stdout.find(EachNodesName.stdout) == -1

    - name: Add worker into cluster using the token generated
      shell:  "{{token.stdout}}"
      when: Clusterinfo.stdout.find(EachNodesName.stdout) == -1
