---
- hosts: all
  remote_user: root

  vars_prompt:
    - name: "MariaPass"
      prompt: "Please enter the password for MariaDB"
      private: yes
      confirm: yes

    - name: "WordPass"
      prompt: "Please enter the password for WordPress"
      private: yes
      confirm: yes

  tasks:
    - name:
      lineinfile:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        insertafter: '    - kube-apiserver'
        line: '    - --service-node-port-range=80-32767'

    - name: Check if Ingress has already been deployed
      shell: kubectl get ingress
      register: deployIngress

    - name: Check if Nginx Ingress Controller has already been deployed
      shell: kubectl get deploy -n ingress-nginx
      register: NginxIngress

    - name: Check if the passwords have already been stored
      shell: kubectl get secret
      register: PassSecret

    - name: Check if MariaDB and WordPress have already been deployed
      shell: kubectl get deploy
      register: DeployData

    - name: Deployment of Ingress
      shell: kubectl create -f https://raw.githubusercontent.com/CloudCommandos/missions/CC/orchestrate-containers/k8s%20files/deployIngress.yml
      when: deployIngress.stdout.find("name-virtual-host-ingress") == -1

    - name: Deployment of Nginx Ingress Controller
      shell: kubectl create -f https://raw.githubusercontent.com/CloudCommandos/missions/CC/orchestrate-containers/k8s%20files/deployIngressController.yml
      when: NginxIngress.stdout.find("nginx-ingress-controller") == -1

    - name: Create and store MariaDB password
      shell: kubectl create secret generic mariadb-pass --from-literal=password={{MariaPass}}
      when: PassSecret.stdout.find("mariadb-pass") == -1

    - name: Create and store WordPress password
      shell: kubectl create secret generic wordpress-pass --from-literal=password={{WordPass}}
      when: PassSecret.stdout.find("wordpress-pass") == -1

    - name: Deployment of MariaDB
      shell: kubectl create -f https://raw.githubusercontent.com/CloudCommandos/missions/CC/orchestrate-containers/k8s%20files/deployMariaDB.yml
      when: DeployData.stdout.find("wordpress-mariadb") == -1

    - name: Deployment of WordPress
      shell: kubectl create -f https://raw.githubusercontent.com/CloudCommandos/missions/CC/orchestrate-containers/k8s%20files/deployWordPress.yml
      when: DeployData.stdout.find("wordpress ") == -1
