    - name: adding apt-key for ceph
      apt_key:
        url: https://download.ceph.com/keys/release.asc
        state: present

    - name: adding ceph repo list
      apt_repository:
        repo: deb https://download.ceph.com/debian-jewel/ stretch main
        state: present

    - name: install ceph-deploy
      apt:
        name:
            - ceph-deploy
        state: present

    - name: Creating my-ceph directory
      file: path=~/my-ceph state=directory

    - name: Creating Ceph cluster
      shell: "ceph-deploy new {{MasterHostname}}"
      args:
        chdir: ~/my-ceph
        creates: ~/my-ceph/ceph.conf

    - name: Adding ceph network into ceph.conf
      lineinfile:
        path: ~/my-ceph/ceph.conf
        line: 'public network = {{NetIP}}'
        state: present

        #- name: Checking the Ceph version
        #shell: "ceph version"
        #register: CephVer
        #changed_when: False

    - name: Install Ceph on Master node
      shell: "ceph-deploy install {{MasterHostname}}"
      args:
        chdir: ~/my-ceph
        #when: CephVer.stdout.find("ceph version") == -1
      changed_when: False

    - name: Deploy initial monitors and create Ceph keys
      shell: "ceph-deploy mon create-initial"
      args:
        chdir: ~/my-ceph
        creates: ~/my-ceph/ceph.bootstrap-rgw.keyring

    - name: Copy config files and keys to master nodes
      shell: "ceph-deploy admin {{MasterHostname}}"
      args:
        chdir: ~/my-ceph
      changed_when: False

    - name: Creating osd for Master node
      shell: ceph-deploy osd create {{MasterHostname}}:/dev/sdb
      args: 
        chdir: ~/my-ceph
        creates: /var/lib/ceph/osd/ceph-0

    - name: Creating meta-data server for CephFS
      shell: "ceph-deploy mds create {{MasterHostname}}"
      args:
        chdir: ~/my-ceph
      changed_when: False
